---
Title: Uso de Symfony Secrets
weight: 40
---

:imagesdir: /images/en/user

== 1. Introducción


Una de las grandes ventajas de utilizar bundles y configuración de Symfony es que podemos aprovechar al máximo las funciones que Symfony ofrece.
Una de esas funciones son los **secrets** (véase el siguiente enlace a la documentación)

- link:https://symfony.com/doc/current/configuration/secrets.html[Symfony Secrets]

Symfony Secrets nos permite almacenar de forma segura valores *sensibles* cifrados en una "vault" (bóveda). Además, estos valores también pueden definirse por entorno.

En nuestra configuración de SAML, esto podría utilizarse para almacenar los certificados y las claves privadas, que no queremos que sean fácilmente accesibles.

Para añadir secrets, comience siguiendo los pasos de configuración en link:https://symfony.com/doc/current/configuration/secrets.html[Symfony's documentation: How to Keep Sensitive Information Secret]

== 2. Añadir un nuevo secret

Después de configurar todo lo necesario para añadir secrets, ya puede añadir nuevos secrets ejecutando el siguiente comando.

Ejecute `php bin/console secrets:set <NAME_OF_ENV_VARIABLE>` (la consola debería mostrar un aviso para establecer el valor)

- p. ej.: `php bin/console secrets:set SAML_SP_PRIVATE_KEY`


== 2. Usar un secret en la configuración

Los secrets pueden añadirse a la configuración como cualquier otra propiedad de entorno, utilizando `'%env(...)'`

El siguiente ejemplo es un fragmento parcial tomado de la configuración de SAML:

[source,yaml]
----
hslavich_onelogin_saml:

  # ...

  sp:

     ...

    # SuiteCRM's private key for SAML (sp)
    privateKey: '%env(SAML_SP_PRIVATE_KEY)%'

    # ...
----

== 3. Limpiar la caché de Symfony

⚠️ Después de realizar un cambio en su `.env.local`, asegúrese de ejecutar `./bin/console cache:clear` desde la raíz o **Reparar y Reconstruir** desde el Menú de Administración.
