---
Title: Выполнение обновления
weight: 30   

aliases:
  - /8.x/admin/upgrading/upgrading-82x-versions/
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 1

//
:sectnums:
:sectnumlevels: 3
//

:experimental:

{{% notice note %}}
В этом разделе описывается обновление версий 8.2.x до более поздних версий.
{{% /notice %}}

{{% notice warning %}}
Если обновляемая версия SuiteCRM меньше 8.2.x - обратитесь к разделу link:../general-info/#_шаги_обновления[Шаги обновления].
{{% /notice %}}

== Скачивание необходимой версии SuiteCRM


.. Скачайте необходимый пакет со страницы https://suitecrm.com/download/
+
При обновлении между версиями SuiteCRM 8.x **нет необходимости в каком-либо специальном пакете обновления.** 
Для этого используется обычный установочный пакет той версии, до которой вы планируете произвести обновление. +
Например, для обновления с версии 8.2.x до версии 8.10.1 используйте пакет `suitecrm-8-10-1.zip`.

.. В установленном экземпляре системы создайте  папку `<your-suitecrm-8-root-folder>/tmp/package/upgrade`.

.. Скопируйте скачанный пакет в созданную папку `<your-suitecrm-8-root-folder>/tmp/package/upgrade`.

== Выполнение обновления

.. ⚠️ Установите необходимые link:../../installation-guide/downloading-installing/#_установка_прав[права доступа^].

.. Из корневой папки SuiteCRM 8 выполните команду: `./bin/console suitecrm:app:upgrade -t "<версия>"`, +
где `<версия>` - название пакета  с устанавливаемой SuiteCRM 8, например: `suitecrm-8-10-1`
+
*Пример:* 
+
[source,console]
-----
./bin/console suitecrm:app:upgrade -t suitecrm-8-10-1
-----

.. ⚠️ Установите ещё раз права доступа.

.. Выполните команду финализации
+
Из корневой папки SuiteCRM 8 выполните команду: `./bin/console suitecrm:app:upgrade-finalize -t "<версия>"`, +
где `<версия>` - название пакета  с устанавливаемой SuiteCRM 8, например: `suitecrm-8-10-1`
+
*Пример:* 
+
[source,console]
-----
./bin/console suitecrm:app:upgrade-finalize -t suitecrm-8-10-1
-----

.. ⚠️ Переустановите ещё раз права доступа.

== Очистка кеша php (опционально)

Если вы используете `OPCache`, `ACP` или другие оптимизаторы,  может потребоваться перезапуск веб-сервера, чтобы применённые изменения вступили в силу.

== Вход в систему

Если все вышеперечисленные шаги были выполнены правильно,  вы сможете войти в обновленный экземпляр SuiteCRM 8.

== Проверка заданий миграции

Некоторые обновления включают задания миграции данных, которые необходимо выполнить после обновления системы. Эти задания преобразуют существующие данные в новые форматы и выполняются 
link:../../async-tasks/[асинхронно] в фоновом режиме.

. Войдите в систему как администратор, откройте в меню пользователя пункт menu:Администрирование[Инструменты администратора> Миграции] и проверьте наличие заданий со статусом *Ожидание*.

. При наличии подобных заданий убедитесь, что
link:../../async-tasks/messenger-setup[воркер] запущен.

. Запустите задания, руководствуясь описанием из раздела
link:../../async-tasks/manual-migration-tasks[Задания миграции].

{{% notice info %}}
Задания миграции были добавлены в SuiteCRM версии 8.10. +
Если система обновляется до более младших версий, этот шаг можно пропустить.
{{% /notice %}}