baseURL = "https://docs.suitecrm.com"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "SuiteCRM Documentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false
enableGitInfo = true
timeout = 47000
ignoreErrors = ["error-remote-getjson"]

[params]
  GitHubRepo  = "https://github.com/SuiteCRM/SuiteDocs/"
  editURL     = "https://github.com/SuiteCRM/SuiteDocs/edit/master/content/"
  issueURL    = "https://github.com/SuiteCRM/SuiteDocs/issues/new?"
  title       = "Documentation for SuiteCRM"
  description = "All you need to know to successfully use SuiteCRM as an End-User, Developer or Administrator, plus Community Guidelines and Technical Blog."
  images      = ["https://docs.suitecrm.com/images/logo-square.png"]
  author      = "SuiteCRM Ltd"
  showVisitedLinks = true
  themeVariant = "suitecrm"

  sidebarAnnouncementText = "NEED PROFESSIONAL SUPPORT?<br>Check out your options"
  sidebarAnnouncementUrl  = "https://suitecrm.com/services/"

[outputs]
home = [ "HTML", "RSS", "JSON"]
section = [ "HTML", "RSS"]

[Languages]

# ------------------------------------------------------------
# ------------------ ENGLISH ---------------------------------
# ------------------------------------------------------------

[Languages.en]
# the following site title appears as PageTitle :: SiteTitle on every page; it will be the tab name on the browser
title = "SuiteCRM Documentation"
#title = "Docs"
weight = 1
languageName = "English"
languageDir = "/"


# ------------------------------------------------------------
# ------------------ SPANISH ---------------------------------
# ------------------------------------------------------------

[Languages.es]
title = "Documentación de SuiteCRM"
weight = 2
languageName = "Español"
languageDir = "/es/"


# ------------------------------------------------------------
# ------------------ RUSSIAN ---------------------------------
# ------------------------------------------------------------

[Languages.ru]
title = "SuiteCRM - Русскоязычная документация"
weight = 3
languageName = "Русский"
languageDir = "/ru/"
