---
title: "Antes de Migrar"
weight: 10
---
:experimental:

Revise lo siguiente antes de comenzar la migración.

{{% notice note %}}
En esta página, "7.14.x+" se refiere a cualquier versión mayor o igual a 7.14.x.
{{% /notice %}}

== Compatibilidad

Asegúrese de que su sistema cumple con la matriz de compatibilidad de la versión de destino de SuiteCRM 8. Consulte la link:../../compatibility-matrix[Matriz de Compatibilidad].

== Actualice primero SuiteCRM 7

Su instancia de SuiteCRM 7 debe estar en la última versión 7.14.x antes de migrar. Realice cualquier paso manual descrito en las notas de la versión de cada versión por la que pase.

== Pruebe antes de producción

Ejecute la migración primero en una instancia de desarrollo o de pruebas. Solo despliegue en producción después de haber realizado las pruebas.

== Haga una copia de seguridad de su instancia

Cree una copia de seguridad tanto de los archivos de su instancia como de su base de datos antes de comenzar.

== APP_ENV

Antes de ejecutar cualquier comando de migración, asegúrese de que su instancia de SuiteCRM 8 tiene `APP_ENV` configurado como `prod` en su archivo `.env` o `.env.local`.

== Archivos personalizados

El proceso de migración puede eliminar archivos o directorios que no sean del núcleo en la carpeta `public/legacy/`. Revise sus personalizaciones antes de migrar.

== Informe de errores

Por defecto, los comandos de migración configuran `error_reporting` en un modo menos estricto para suprimir advertencias:
`E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING`

Para aplicar un modo más estricto, añada `-vvv` a cada comando. Esto configura `error_reporting` como `E_ALL`.
